INSERT INTO USERS VALUES ('admin','admin','ADMIN','1');

INSERT INTO CONTAINERS (CONTAINER_IMAGE) VALUES('ubuntu');
INSERT INTO CONTAINERS (CONTAINER_IMAGE) VALUES('fedora');

INSERT INTO DOCKER_SERVERS (SERVER_NAME,SERVER_ADDRESS) VALUES('test localhost server','http://localhost:2375')