CREATE TABLE USERS (
  NAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  PRIMARY KEY(NAME)
);

CREATE TABLE CONTAINERS (
  CONTAINER_ID INTEGER NOT NULL,
  CONTAINER_IMAGE VARCHAR(50),
  PRIMARY KEY(CONTAINER_ID)
);