DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CONTAINERS;
DROP TABLE IF EXISTS DOCKER_SERVERS;



CREATE TABLE USERS (
  NAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  ROLE VARCHAR(50) NOT NULL,
  ENABLED TINYINT NOT NULL DEFAULT 1 ,
  PRIMARY KEY(NAME)
);

CREATE TABLE CONTAINERS (
  CONTAINER_ID INTEGER NOT NULL AUTO_INCREMENT,
  CONTAINER_IMAGE VARCHAR(50),
  PRIMARY KEY(CONTAINER_ID)
);

CREATE TABLE DOCKER_SERVERS (
  SERVER_ID INTEGER NOT NULL AUTO_INCREMENT,
  SERVER_NAME VARCHAR(50),
  SERVER_ADDRESS VARCHAR(50),
  PRIMARY KEY(SERVER_ID)
);